# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d269d7fe444946e1def0b5f09f4009252927b0e8788025c77c32272046f20c1135118e03071f1ed2a6625bd92d33e4ed28af9e4ad4b77f675bf8e4d342505ad

test:
  secret_key_base: 382d85425165a6b98d24b18952c19146650b5656122761a428648e26c150c89b52efef1d68ae01a45e9a278aa4bde5075c39944f656f9f955f1f7b18a61861dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
